name: Lighthouse CI
on: repository_dispatch
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://wordpress.org
          uploadArtifacts: true # save results as an action artifact
          configPath: ./lighthouserc.json

      - name: Create file
        run: echo "${{ steps.LHCIAction.outputs.manifest }}" > something.html

      - name: Commit and push changes
        run: |
          git config --local user.email "dufresnesteven@github.com"
          git config --local user.name "StevenDufresne"
          git add something.html
          git commit -m "Add something.html"
          git push origin HEAD:stats-branch
