name: Lighthouse CI
on: repository_dispatch
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://wordpress.org
          uploadArtifacts: true # save results as an action artifact
          configPath: ./lighthouserc.json

      - name: Create file
        run: echo "${{ steps.LHCIAction.outputs.manifest }}" > something.html

      - name: Add all the plugin files
        run: |
            git add *

      - name: Commit & Push changes
        uses: actions-js/push@stats-branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
